### ISSUE TITLE
Moving testinfra to a github organization

### ISSUE THREAD

**Issue by philpep** [pytest-dev/pytest-testinfra#484]
Hi testinfra users and contributors.

I'm wondering how to offer the best future for testinfra development. After
discussing about this with some contributors, I consider moving testinfra to a
github organization.

Why ? While I'm still happy to maintain the code, I've less time to do it.
Also I'm not an expert of all topics covered by testinfra, especially the
ansible integration is quite tricky, even for me, and I'm totally ignorant
with windows.

I recently added @ianw, @decentral1se and @ssbarnea as maintainers, so they
can fix bugs and release quickly when I'm not available.

Now I consider moving testinfra to a github organization, this has several
advantages:

* Joining a developers community is good for long term maintenance
* People from the organization have a good potentiality to help maintaining
  the project.
* Organization may have tools, CI, workflows which can help maintaining the
  project.
* Users usually have a better maintenance trust in project which belong to a
  known organization

I think the criteria for choosing includes:

* First, are they open to take testinfra ?
* does testinfra match the organization policy ?
* Will we be allowed to have full github administrative permissions on the
  project (this is useful for CI setup etc)
* Number of people
* Links between testinfra and others projects from the organization (python,
  pytest, infrastructure testing)

At the time of writing, we have some potential candidates:

* https://github.com/pycontribs
* https://github.com/pytest-dev
* https://opendev.org/ (not sure they have a dedicated github organization)
* https://github.com/ansible

**Comment by philpep** [comment]
About pytest-dev, they seems to be open for any pytest related project to join the organization. The process is described here: https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#submitting-plugins-to-pytest-dev

I think testinfra matches all the criteria, *except* that the project name is not prefixed by `pytest-` (and I think renaming the project is out of scope for now).
Still a good candidate for me because, testinfra is highly related to pytest and they are a good community with very active (and nice) people.

**Comment by ssbarnea** [comment]
@philpep if testinfra is a pytest-plugin moving under pytest-dev is almost a total winner. 

My only concern is around "administrative permission" needed for enabling new github integrations and bigger organizations. This proved to be a real PITA in several cases for me and even blocker. 

For example I cannot enable Azure pipelines for Molecule because I have no access and because... policy. The bigger the organization the bigger the policy. Some projects died by being adopted by a bigger rigid organization and that it I would like to avoid.

So if one of testinfra maintainers is also an admin on the organization and we get the agreement that configuring additional integration would not be an issue, we should be ok. To be honest I would be proud to join the bigger pytest team and glad to transfer my pycontribs/pytest-molecule to pytest-dev - it gives better visibility.

PS. For PyContribs, I am ok to give org admin rights to all involved here, as they seem trustworthy and decent not to touch other projects (or careful enough not to activate an integration that affects other unrelated repositories).

**Comment by decentral1se** [comment]
Adding to `pytest-dev` (if you can get over the naming issue) and getting existing maintainers here having access there sounds like it would be a great solution.

**Comment by ssbarnea** [comment]
@philpep I hope you are still interested about the more. Out of curiosity what is the main issue with renaming the git repository name or the package name? AFAIK, they do not have to match. Based on how I read the docs, I have the impression that the docs wants packages named with the prefix, it does not say anything about repository name.

I still hope pytest-dev team will accept the exemption from the rule, basically for not breaking the big number of users.
